models:
  IAModel:
      name: string
      avatar: string nullable
      ration: float default:2
      batch_size: integer default:32
      shuffle: boolean default:true
      training_epochs: integer default:5
      dataset_id: unsignedInteger
      relationships:  
        belongsTo: Dataset

  Dataset:
    name: string
    relationships:
      hasMany: Model

seeders: IAModel, Dataset